version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/
    overwrite: true
  - source: /components.html
    destination: /var/www/html/
    overwrite: true
  - source: /assets
    destination: /var/www/html/assets
    overwrite: true
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
