#!/bin/bash

# Detect OS and install apache2/httpd
if [ -f /etc/debian_version ]; then
    # Ubuntu/Debian
    apt update -y
    apt install -y apache2
elif [ -f /etc/redhat-release ]; then
    # Amazon Linux/RHEL
    yum update -y
    yum install -y httpd
fi
